### ISSUE TITLE
Unify module / rover / VJ-Net38

### ISSUE THREAD

**Issue by grena** [nidup/ldjam38#19]
There are somtimes module, rover & VJ-Net38, but they refer to the same thing

**Comment by nidup** [comment]
Yep we need to be extra clear, we discuss / controll a rover an exploration/builder bot

**Comment by nidup** [comment]
Imho,
Rover = the exploration bot that we undock to explore the world
Module = an infra building (energy, communication, refinery, extractor) installed by the recon on a Biome
VJ-Net38 is the name of our poetic recon
